name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake SVG
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub contribution snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Jhosep2022
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Deploy SVGs to GitHub Pages (branch output)
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
